spring:
  application:
    name: library-api

  config:
    import: optional:classpath:db_credentials.properties

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

