spring:
  application:
    name: library-api

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  config:
    import: optional:classpath:credentials.properties

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

